[package]
name = "lsass_dump_rs"
version = "0.1.0"
edition = "2021"

[dependencies.windows-sys]
version="0.52"
features=[
    "Win32_Security",
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_ToolHelp",
]